stages:
  - hexo_run
  - deploy_hexo

cache:
  paths:
    - node_modules/

before_script:
  - export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
  - export COMMIT_TIME_STR=$(date -d @$COMMIT_TIME +%Y%m%d%H%M%S)

hexo_run_job:
  stage: hexo_run
  only:
    - master
  script:
    - test -e package.json && npm install

deploy_hexo_job:
  stage: deploy_hexo
  script:
    # 发布
    - hexo clean
    - hexo generate
    # 压缩
    - cd public
    - zip -r $COMMIT_TIME_STR.zip ./
    - echo "version:$COMMIT_TIME_STR"
    - echo "$DEV_URL"
    # 部署blog
    - lftp sftp://$DEV_URL -e "user $DEV_USER $DEV_PASS; cd /root/blog; put $COMMIT_TIME_STR.zip; bye"
    - sshpass -p "$DEV_PASS" ssh -o StrictHostKeyChecking=no $DEV_USER@$DEV_URL "cd /root/blog;unzip -o ./$COMMIT_TIME_STR.zip;rm -Rf ./$COMMIT_TIME_STR.zip;"
    - sshpass -p "$DEV_PASS" ssh -o StrictHostKeyChecking=no $DEV_USER@$DEV_URL "service nginx restart;"
    # 删除压缩包
    - rm -Rf ./$COMMIT_TIME_STR.zip
  artifacts:
    paths:
      - public
  only:
    - master
