image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm i hexo-theme-ayer -S
  - npm install
  - npm install hexo-cli -g
  - test -e package.json && npm install
  - hexo clean
  - hexo generate

pages:
  script:
    - hexo generate
  artifacts:
    paths:
      - public
  only:
    - master
